static	char	*errmenu[] = {
"",
"zo",
"he",
"he",
"he",
"he",
"he",
"he",
"he",
"he",
"pp",
"pp",
"tc",
"tc",
"tc",
"tc",
"tc",
"sb",
"dc",
"dc",
"dc",
"ti",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"al",
"he",
"he",
"he",
"he",
"he",
"he",
"he",
"he",
"ms",
"ti",
"ms",
""};
static	char	*errmes[] = {
"123456789012345678901234567",
"Zone   temp scatter > dev",
"Heater temp error   > dev",
"Heater temp scatter > dev",
"Current sensor failed on",
"Voltage sensor failed on",
"Heater element failed on !!",
"Heater element failed off",
"Voltage sensor failed off",
"Current sensor failed off",
"Power panel protocol error",
"Power panel buss failure",
"Floating point exception",
"Backwards thermocouple",
"Shorted thermocouple",
"Very hot thermocouple",
"Open thermocouple",
"Select buss failure",
"DCU timer stuck on",
"DCU timer stuck off",
"PIO/DCU status invalid",
"Junction temp discrepancy",
"fase current < lower limit",
"fase current > upper limit",
"fase current indefinite",
"fase voltage < lower limit",
"fase voltage > upper limit",
"fase voltage indefinite",
"panel current < lower limit",
"panel current > upper limit",
"panel current indefinite",
"hkp voltage < lower limit",
"hkp voltage > upper limit",
"hkp voltage indefinite",
"Remote  sensor failed off",
"Remote  sensor failed on",
"Heater failed on ?! hvCR",
"Heater failed on ?! hVcR",
"Heater failed on ?! hVCr",
"Heater failed off ? HvcR",
"Heater failed off ? HvCr",
"Heater failed off ? HVcr",
"Timeout !!",
"Implausible junction temp",
"task restarted",
""};
