#define	ERRZSC	1
#define	ERRHER	2
#define	ERRHSC	3
#define	ERRCON	4
#define	ERRVON	5
#define	ERRHON	6
#define	ERRHOF	7
#define	ERRVOF	8
#define	ERRCOF	9
#define	ERRPPE	10
#define	ERRPKP	11
#define	ERRFPE	12
#define	ERRBACK 13
#define	ERRSHRT 14
#define	ERRMELT 15
#define	ERROPEN 16
#define	ERRMER	17
#define	ERRTON	18
#define	ERRTOF	19
#define	ERRDST	20
#define	ERRIJT	21
#define	ERRFCL	22
#define	ERRFCU	23
#define	ERRFCI	24
#define	ERRFVL	25
#define	ERRFVU	26
#define	ERRFVI	27
#define	ERRPCL	28
#define	ERRPCU	29
#define	ERRPCI	30
#define	ERRHVL	31
#define	ERRHVU	32
#define	ERRHVI	33
#define	ERRROF	34
#define	ERRRON	35
#define	ERROOII	36
#define	ERROIOI	37
#define	ERROIIO	38
#define	ERRIOOI	39
#define	ERRIOIO	40
#define	ERRIIOO	41
#define	ERRTIME 42
#define	ERRJTL  43
#define	ERRTEXC 44
