#define	HOVEN	hoven_
#define	DOVEN	doven_
#define	EOVEN	eoven_
#define	GOVEN	goven_
#define	POVEN	poven_
#define	BOVEN	boven_
#define	WOVEN	woven_
#define	OOVEN	ooven_
#define	HGKEY	hgkey_
#define	THGKEY	thgkey_
#define	HPAGEH	hpageh_
#define	HCLGST	hclgst_
#define	FLGKEY	flgkey_
#define	LGDATA	lgdata_
#define	BACKUP	backup_
#define	PTIMESTAMP	ptimep_
#define	GPAN_LOC	gpanlc_
#define	TC_LOC	tcloc_
#define	HE_LOC	heloc_
#define	DATAB_XTMP	databp_
#define	XTC_LOC	xtcloc_
#define	XHE_LOC	xheloc_
#define	HE_MAP	hemap_
#define GTTNOW	gttnow_
#define GHTNOW	ghtnow_
#define GHPNOW	ghpnow_
#define	TIMCUR	timcur_
#define DECISLEEP decisp_
